---
abstract: 'Simple socket transport for Test::Reporter'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Reporter-Transport-Socket
no_index:
  directory:
    - inc
    - t
provides:
  Test::Reporter::Transport::Socket:
    file: lib/Test/Reporter/Transport/Socket.pm
    version: 0.04
requires:
  Config::Perl::V: 0.11
  IO::Socket::INET: 0
  Storable: 0
  Test::Reporter: 1.56
  Test::Reporter::Transport: 1.56
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/test-reporter-transport-socket/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/test-reporter-transport-socket.git
version: 0.04
